#!/bin/bash
pkill bastion.py
cd /usr/local/bin/discord/
let foo1=$(expr $(wc -l discord_corpus | cut -d ' ' -f 1) - 200000)
if [ "$foo1" -ge "0" ]
        then
                head -n $foo1 discord_corpus >> discord_archive
                tail -n +$foo1 discord_corpus > corpus_tmp
		mv corpus_tmp discord_corpus
fi
python3 bastion.py
