#!/bin/bash
pkill screen
cd /usr/local/bin/bastionbot
let foo1=$(expr $(wc -l discord_corpus | cut -d ' ' -f 1) - 200000)
if [ "$foo1" -ge "0" ]
        then
                head -n $foo1 discord_corpus >> discord_archive
                tail -n +$foo1 discord_corpus > corpus_tmp
		mv corpus_tmp discord_corpus
fi
screen -d -m python3 bastion.py
